services:
  app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: postgres_db
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
